name: board

services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
